keys:
  - &admin_donny age16eauxtjmcgmewc6mdk668awu7lqk6xslh34s6lv79a2ztrrdzg4qm4tkn7
creation_rules:
  # - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *admin_donny
