keys:
  - &admin_donny age1w5py6x8t2gl4wffdf7jj06t2kpkkavrnyguwu9xswz795e97t93qwx4xy5
creation_rules:
  # - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *admin_donny
